---
name: CI

on:
  push:
    branches-ignore:
      - 'feature/latest'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Requirements
        run: |
          pip install -qr requirements.txt
          pip freeze
          pip check

      - name: Run Make
        run: make

      - name: Publish Code Coverage
        uses: paambaati/codeclimate-action@v3.1.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: coverage xml
          coverageLocations: |
            ${{github.workspace}}/coverage.xml:coverage.py

      - name: Build
        run: make build
