---
name: Latest

on:
  push:
    branches:
      - feature/latest
  schedule:
    - cron: '0 0 1,15 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Requirements
        run: |
          cut -d= -f1 requirements.txt > /tmp/requirements-latest.txt
          pip install -qr /tmp/requirements-latest.txt
          pip freeze
          pip check

      - name: Bandit
        run: bandit -r .

      - name: Test
        run: make test

      - name: Build
        run: make build
